### ISSUE TITLE
Generated *mut *mut type causes illegal hardware instruction.

### ISSUE THREAD

**Issue by pekhee** [crabtw/rust-bindgen#218] opened 2015-06-18 03:03 UTC
Bindgen for CZMQ generated:

    pub fn zsock_destroy(self_p: *mut *mut zsock_t) -> ();

Casting a `*mut zsock_t` to `*mut *mut zsock_t` and passing it to `zsock_destroy` causes "Illegal hardware instruction".
I could get around this with changing `*mut *mut zsock_t` to `&*mut zsock_t`.

I don't know what's going on, but maybe this is a bug in bindgen.

**Comment by oli-obk** [comment] 2015-08-07 08:00
what's the c function's signature?

**Comment by dimbleby** [comment] 2015-08-15 13:54
> Casting a `*mut zsock_t` to `*mut *mut zsock_t`...

... is surely wrong, because a pointer to a `zsock_t` is not the same as a pointer to a pointer to a `zsock_t`.

**Comment by nox** [comment] 2016-03-10 11:10
Closing this.

**Closed by nox** 2016-03-10 11:10 UTC

**Comment by pekhee** [comment] 2016-03-21 01:38
> is surely wrong, because a pointer to a zsock_t is not the same as a pointer to a pointer to a zsock_t.
Which was my point.

**Comment by nox** [comment] 2016-03-21 09:02
@pekhee Yes?

**Comment by dimbleby** [comment] 2016-03-21 11:54
@pekhee: what you described in your bug report is a bad cast in your own code, not a bug in the code produced by bindgen.

If that's not what you intended, suggest providing more details.
